/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) w_totalF_nmpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {14, 1, 1};

/* w_totalF_nmpc_expl_vde_adj:(i0[10],i1[10],i2[4],i3[4])->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[2]? arg[2][3] : 0;
  a01=5.0000000000000000e-01;
  a02=arg[1]? arg[1][9] : 0;
  a02=(a01*a02);
  a03=(a00*a02);
  a04=arg[2]? arg[2][2] : 0;
  a05=arg[1]? arg[1][8] : 0;
  a05=(a01*a05);
  a06=(a04*a05);
  a03=(a03+a06);
  a06=arg[2]? arg[2][1] : 0;
  a07=arg[1]? arg[1][7] : 0;
  a07=(a01*a07);
  a08=(a06*a07);
  a03=(a03+a08);
  a08=arg[0]? arg[0][6] : 0;
  a09=casadi_sq(a08);
  a10=arg[0]? arg[0][7] : 0;
  a11=casadi_sq(a10);
  a09=(a09+a11);
  a11=arg[0]? arg[0][8] : 0;
  a12=casadi_sq(a11);
  a09=(a09+a12);
  a12=arg[0]? arg[0][9] : 0;
  a13=casadi_sq(a12);
  a09=(a09+a13);
  a09=sqrt(a09);
  a13=(a03/a09);
  a14=(a08+a08);
  a08=(a08/a09);
  a15=(a08/a09);
  a03=(a15*a03);
  a16=(a12/a09);
  a17=(a16/a09);
  a18=(a06*a05);
  a19=(a04*a07);
  a18=(a18-a19);
  a19=arg[1]? arg[1][6] : 0;
  a01=(a01*a19);
  a19=(a00*a01);
  a18=(a18-a19);
  a19=(a17*a18);
  a03=(a03+a19);
  a19=(a11/a09);
  a20=(a19/a09);
  a21=(a00*a07);
  a22=(a06*a02);
  a21=(a21-a22);
  a22=(a04*a01);
  a21=(a21-a22);
  a22=(a20*a21);
  a03=(a03+a22);
  a22=(a10/a09);
  a23=(a22/a09);
  a04=(a04*a02);
  a00=(a00*a05);
  a04=(a04-a00);
  a06=(a06*a01);
  a04=(a04-a06);
  a06=(a23*a04);
  a03=(a03+a06);
  a06=(a09+a09);
  a03=(a03/a06);
  a00=(a14*a03);
  a13=(a13-a00);
  a00=arg[2]? arg[2][0] : 0;
  a24=(a08*a00);
  a25=arg[1]? arg[1][5] : 0;
  a26=(a24*a25);
  a27=(a22*a00);
  a28=arg[1]? arg[1][4] : 0;
  a29=(a27*a28);
  a26=(a26-a29);
  a29=(a08*a25);
  a30=(a22*a28);
  a29=(a29-a30);
  a30=arg[1]? arg[1][3] : 0;
  a31=(a19*a30);
  a29=(a29+a31);
  a31=(a00*a29);
  a26=(a26+a31);
  a31=(a19*a00);
  a32=(a31*a30);
  a26=(a26+a32);
  a32=(a26/a09);
  a13=(a13+a32);
  a15=(a15*a26);
  a26=(a16*a00);
  a32=(a26*a28);
  a33=(a31*a25);
  a32=(a32-a33);
  a33=(a24*a30);
  a32=(a32+a33);
  a33=(a16*a28);
  a34=(a19*a25);
  a33=(a33-a34);
  a34=(a08*a30);
  a33=(a33+a34);
  a34=(a00*a33);
  a32=(a32+a34);
  a20=(a20*a32);
  a15=(a15+a20);
  a20=(a16*a30);
  a34=(a22*a25);
  a35=(a08*a28);
  a34=(a34+a35);
  a20=(a20-a34);
  a34=(a00*a20);
  a35=(a27*a25);
  a24=(a24*a28);
  a35=(a35+a24);
  a34=(a34-a35);
  a35=(a26*a30);
  a34=(a34+a35);
  a23=(a23*a34);
  a15=(a15+a23);
  a26=(a26*a25);
  a31=(a31*a28);
  a26=(a26+a31);
  a27=(a27*a30);
  a26=(a26+a27);
  a25=(a16*a25);
  a28=(a19*a28);
  a25=(a25+a28);
  a30=(a22*a30);
  a25=(a25+a30);
  a00=(a00*a25);
  a26=(a26+a00);
  a17=(a17*a26);
  a15=(a15+a17);
  a15=(a15/a06);
  a14=(a14*a15);
  a13=(a13-a14);
  if (res[0]!=0) res[0][6]=a13;
  a04=(a04/a09);
  a10=(a10+a10);
  a13=(a10*a03);
  a04=(a04-a13);
  a34=(a34/a09);
  a04=(a04+a34);
  a10=(a10*a15);
  a04=(a04-a10);
  if (res[0]!=0) res[0][7]=a04;
  a21=(a21/a09);
  a11=(a11+a11);
  a04=(a11*a03);
  a21=(a21-a04);
  a32=(a32/a09);
  a21=(a21+a32);
  a11=(a11*a15);
  a21=(a21-a11);
  if (res[0]!=0) res[0][8]=a21;
  a18=(a18/a09);
  a12=(a12+a12);
  a03=(a12*a03);
  a18=(a18-a03);
  a26=(a26/a09);
  a18=(a18+a26);
  a12=(a12*a15);
  a18=(a18-a12);
  if (res[0]!=0) res[0][9]=a18;
  a29=(a08*a29);
  a20=(a22*a20);
  a29=(a29+a20);
  a33=(a19*a33);
  a29=(a29+a33);
  a25=(a16*a25);
  a29=(a29+a25);
  if (res[0]!=0) res[0][10]=a29;
  a29=(a16*a05);
  a25=(a19*a02);
  a29=(a29-a25);
  a25=(a08*a07);
  a29=(a29+a25);
  a25=(a22*a01);
  a29=(a29-a25);
  if (res[0]!=0) res[0][11]=a29;
  a29=(a22*a02);
  a25=(a08*a05);
  a29=(a29+a25);
  a25=(a16*a07);
  a29=(a29-a25);
  a25=(a19*a01);
  a29=(a29-a25);
  if (res[0]!=0) res[0][12]=a29;
  a08=(a08*a02);
  a22=(a22*a05);
  a08=(a08-a22);
  a19=(a19*a07);
  a08=(a08+a19);
  a16=(a16*a01);
  a08=(a08-a16);
  if (res[0]!=0) res[0][13]=a08;
  return 0;
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int w_totalF_nmpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int w_totalF_nmpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real w_totalF_nmpc_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* w_totalF_nmpc_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* w_totalF_nmpc_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* w_totalF_nmpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* w_totalF_nmpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
