/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) w_totalF_nmpc_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {13, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[33] = 
  {14, 14, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 4, 8, 12,
  16, 10, 11, 12, 13, 10, 11, 12,
  13, 10, 11, 12, 13, 10, 11, 12,
  13};

/* w_totalF_nmpc_cost_y_hess:(i0[10],i1[4],i2[0],i3[13],i4[],i5[4])->(o0[14x14,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62;
  a00=arg[5]? arg[5][0] : 0;
  a01=arg[3]? arg[3][7] : 0;
  a02=arg[0]? arg[0][6] : 0;
  a03=(a02*a00);
  a04=arg[0]? arg[0][7] : 0;
  a05=arg[5]? arg[5][1] : 0;
  a06=(a04*a05);
  a03=(a03+a06);
  a06=arg[0]? arg[0][8] : 0;
  a07=arg[5]? arg[5][2] : 0;
  a08=(a06*a07);
  a03=(a03+a08);
  a08=arg[0]? arg[0][9] : 0;
  a09=arg[5]? arg[5][3] : 0;
  a10=(a08*a09);
  a03=(a03+a10);
  a10=casadi_sq(a03);
  a11=(a06*a05);
  a12=(a02*a09);
  a13=(a04*a07);
  a12=(a12+a13);
  a11=(a11-a12);
  a12=(a08*a00);
  a11=(a11+a12);
  a12=casadi_sq(a11);
  a10=(a10+a12);
  a12=1.0000000000000000e-03;
  a10=(a10+a12);
  a10=sqrt(a10);
  a12=(a01/a10);
  a13=(a12*a07);
  a14=(a04*a09);
  a15=(a02*a07);
  a14=(a14-a15);
  a15=(a06*a00);
  a14=(a14+a15);
  a15=(a08*a05);
  a14=(a14-a15);
  a15=(a12/a10);
  a16=(a03+a03);
  a17=(a16*a00);
  a18=(a11+a11);
  a19=(a18*a09);
  a17=(a17-a19);
  a19=(a10+a10);
  a17=(a17/a19);
  a20=(a15*a17);
  a21=(a14*a20);
  a21=(a13+a21);
  a22=(a11/a10);
  a22=(a22/a10);
  a23=arg[3]? arg[3][8] : 0;
  a24=(a22*a23);
  a25=(a03*a14);
  a04=(a04*a00);
  a02=(a02*a05);
  a04=(a04-a02);
  a06=(a06*a09);
  a04=(a04-a06);
  a08=(a08*a07);
  a04=(a04+a08);
  a08=(a04*a11);
  a25=(a25+a08);
  a25=(a25/a10);
  a25=(a25/a10);
  a08=(a25*a01);
  a24=(a24+a08);
  a08=(a03*a04);
  a06=(a14*a11);
  a08=(a08-a06);
  a08=(a08/a10);
  a08=(a08/a10);
  a06=arg[3]? arg[3][6] : 0;
  a02=(a08*a06);
  a24=(a24+a02);
  a24=(a24/a19);
  a02=(a00+a00);
  a02=(a24*a02);
  a26=(a14*a00);
  a27=(a03*a07);
  a28=(a26-a27);
  a29=(a11*a05);
  a30=(a04*a09);
  a31=(a29+a30);
  a28=(a28-a31);
  a28=(a28/a10);
  a31=(a25*a17);
  a28=(a28-a31);
  a28=(a28/a10);
  a31=(a25/a10);
  a32=(a31*a17);
  a28=(a28-a32);
  a28=(a01*a28);
  a32=(a09/a10);
  a33=(a22*a17);
  a32=(a32+a33);
  a32=(a32/a10);
  a33=(a22/a10);
  a34=(a33*a17);
  a32=(a32+a34);
  a32=(a23*a32);
  a28=(a28-a32);
  a32=(a04*a00);
  a34=(a03*a05);
  a35=(a32-a34);
  a36=(a11*a07);
  a37=(a14*a09);
  a38=(a36+a37);
  a35=(a35+a38);
  a35=(a35/a10);
  a38=(a08*a17);
  a35=(a35-a38);
  a35=(a35/a10);
  a38=(a08/a10);
  a39=(a38*a17);
  a35=(a35-a39);
  a35=(a06*a35);
  a28=(a28+a35);
  a28=(a28/a19);
  a35=(a24/a19);
  a39=(a17+a17);
  a39=(a35*a39);
  a28=(a28-a39);
  a39=(a16*a28);
  a39=(a02+a39);
  a21=(a21+a39);
  a39=(a06/a10);
  a40=(a39*a05);
  a41=(a39/a10);
  a42=(a41*a17);
  a43=(a04*a42);
  a43=(a40+a43);
  a21=(a21+a43);
  a21=(a00*a21);
  a43=(a39*a07);
  a44=(a14*a42);
  a44=(a43+a44);
  a45=(a23/a10);
  a45=(a45/a10);
  a17=(a45*a17);
  a46=(a12*a05);
  a47=(a04*a20);
  a47=(a46+a47);
  a17=(a17+a47);
  a28=(a18*a28);
  a47=(a09+a09);
  a47=(a24*a47);
  a28=(a28-a47);
  a17=(a17+a28);
  a44=(a44-a17);
  a44=(a09*a44);
  a17=(a12*a00);
  a28=(a03*a20);
  a28=(a17-a28);
  a48=(a39*a09);
  a49=(a11*a42);
  a49=(a48+a49);
  a28=(a28+a49);
  a28=(a07*a28);
  a44=(a44+a28);
  a39=(a39*a00);
  a42=(a03*a42);
  a42=(a39-a42);
  a12=(a12*a09);
  a20=(a11*a20);
  a20=(a12+a20);
  a42=(a42-a20);
  a42=(a05*a42);
  a44=(a44+a42);
  a21=(a21+a44);
  a21=(-a21);
  if (res[0]!=0) res[0][0]=a21;
  a21=(a16*a05);
  a44=(a18*a07);
  a21=(a21-a44);
  a21=(a21/a19);
  a44=(a15*a21);
  a42=(a14*a44);
  a42=(a12-a42);
  a20=(a05+a05);
  a20=(a24*a20);
  a28=(a14*a05);
  a49=(a03*a09);
  a50=(a28+a49);
  a51=(a11*a00);
  a52=(a04*a07);
  a53=(a51-a52);
  a50=(a50+a53);
  a50=(a50/a10);
  a53=(a25*a21);
  a50=(a50-a53);
  a50=(a50/a10);
  a53=(a31*a21);
  a50=(a50-a53);
  a50=(a01*a50);
  a53=(a07/a10);
  a54=(a22*a21);
  a53=(a53+a54);
  a53=(a53/a10);
  a54=(a33*a21);
  a53=(a53+a54);
  a53=(a23*a53);
  a50=(a50-a53);
  a53=(a04*a05);
  a54=(a03*a00);
  a55=(a53+a54);
  a56=(a11*a09);
  a57=(a14*a07);
  a58=(a56-a57);
  a55=(a55-a58);
  a55=(a55/a10);
  a58=(a08*a21);
  a55=(a55-a58);
  a55=(a55/a10);
  a58=(a38*a21);
  a55=(a55-a58);
  a55=(a06*a55);
  a50=(a50+a55);
  a50=(a50/a19);
  a55=(a21+a21);
  a55=(a35*a55);
  a50=(a50-a55);
  a55=(a16*a50);
  a55=(a20+a55);
  a42=(a42-a55);
  a55=(a41*a21);
  a58=(a04*a55);
  a58=(a39-a58);
  a42=(a42+a58);
  a58=(a00*a42);
  a59=(a04*a44);
  a59=(a17-a59);
  a21=(a45*a21);
  a59=(a59-a21);
  a50=(a18*a50);
  a21=(a07+a07);
  a24=(a24*a21);
  a50=(a50-a24);
  a59=(a59-a50);
  a50=(a14*a55);
  a50=(a48-a50);
  a59=(a59-a50);
  a50=(a09*a59);
  a21=(a03*a44);
  a21=(a46-a21);
  a60=(a11*a55);
  a60=(a43+a60);
  a21=(a21+a60);
  a60=(a07*a21);
  a50=(a50+a60);
  a55=(a03*a55);
  a55=(a40-a55);
  a44=(a11*a44);
  a44=(a13+a44);
  a55=(a55-a44);
  a44=(a05*a55);
  a50=(a50+a44);
  a58=(a58-a50);
  if (res[0]!=0) res[0][1]=a58;
  a50=(a16*a07);
  a44=(a18*a05);
  a50=(a50+a44);
  a50=(a50/a19);
  a44=(a15*a50);
  a60=(a14*a44);
  a60=(a17-a60);
  a61=(a05/a10);
  a62=(a22*a50);
  a61=(a61-a62);
  a61=(a61/a10);
  a62=(a33*a50);
  a61=(a61-a62);
  a61=(a23*a61);
  a57=(a57+a54);
  a53=(a53-a56);
  a57=(a57+a53);
  a57=(a57/a10);
  a53=(a25*a50);
  a57=(a57-a53);
  a57=(a57/a10);
  a53=(a31*a50);
  a57=(a57-a53);
  a57=(a01*a57);
  a61=(a61+a57);
  a52=(a52-a49);
  a51=(a51+a28);
  a52=(a52-a51);
  a52=(a52/a10);
  a51=(a08*a50);
  a52=(a52-a51);
  a52=(a52/a10);
  a51=(a38*a50);
  a52=(a52-a51);
  a52=(a06*a52);
  a61=(a61+a52);
  a61=(a61/a19);
  a52=(a50+a50);
  a52=(a35*a52);
  a61=(a61-a52);
  a52=(a16*a61);
  a24=(a24+a52);
  a60=(a60-a24);
  a24=(a41*a50);
  a52=(a04*a24);
  a52=(a48+a52);
  a60=(a60-a52);
  a52=(a00*a60);
  a51=(a03*a44);
  a51=(a13-a51);
  a28=(a11*a24);
  a28=(a40-a28);
  a51=(a51-a28);
  a28=(a07*a51);
  a50=(a45*a50);
  a49=(a04*a44);
  a49=(a12+a49);
  a50=(a50+a49);
  a61=(a18*a61);
  a20=(a20+a61);
  a50=(a50+a20);
  a20=(a14*a24);
  a20=(a39-a20);
  a50=(a50+a20);
  a20=(a09*a50);
  a28=(a28-a20);
  a44=(a11*a44);
  a44=(a46-a44);
  a24=(a03*a24);
  a24=(a43-a24);
  a44=(a44+a24);
  a24=(a05*a44);
  a28=(a28+a24);
  a52=(a52-a28);
  if (res[0]!=0) res[0][2]=a52;
  a28=(a16*a09);
  a24=(a18*a00);
  a28=(a28+a24);
  a28=(a28/a19);
  a41=(a41*a28);
  a24=(a04*a41);
  a43=(a43-a24);
  a15=(a15*a28);
  a24=(a14*a15);
  a46=(a46+a24);
  a24=(a00/a10);
  a22=(a22*a28);
  a24=(a24-a22);
  a24=(a24/a10);
  a33=(a33*a28);
  a24=(a24-a33);
  a23=(a23*a24);
  a37=(a37-a34);
  a36=(a36+a32);
  a37=(a37+a36);
  a37=(a37/a10);
  a25=(a25*a28);
  a37=(a37-a25);
  a37=(a37/a10);
  a31=(a31*a28);
  a37=(a37-a31);
  a01=(a01*a37);
  a23=(a23+a01);
  a30=(a30+a27);
  a26=(a26-a29);
  a30=(a30-a26);
  a30=(a30/a10);
  a08=(a08*a28);
  a30=(a30-a08);
  a30=(a30/a10);
  a38=(a38*a28);
  a30=(a30-a38);
  a06=(a06*a30);
  a23=(a23+a06);
  a23=(a23/a19);
  a19=(a28+a28);
  a35=(a35*a19);
  a23=(a23-a35);
  a16=(a16*a23);
  a47=(a47+a16);
  a46=(a46+a47);
  a43=(a43-a46);
  a46=(a00*a43);
  a04=(a04*a15);
  a13=(a13-a04);
  a45=(a45*a28);
  a13=(a13-a45);
  a18=(a18*a23);
  a02=(a02+a18);
  a13=(a13-a02);
  a14=(a14*a41);
  a40=(a40+a14);
  a13=(a13+a40);
  a40=(a09*a13);
  a14=(a03*a15);
  a12=(a12-a14);
  a14=(a11*a41);
  a39=(a39-a14);
  a12=(a12-a39);
  a39=(a07*a12);
  a40=(a40+a39);
  a11=(a11*a15);
  a17=(a17-a11);
  a03=(a03*a41);
  a48=(a48-a03);
  a17=(a17+a48);
  a48=(a05*a17);
  a40=(a40+a48);
  a46=(a46-a40);
  if (res[0]!=0) res[0][3]=a46;
  if (res[0]!=0) res[0][4]=a58;
  a21=(a09*a21);
  a59=(a07*a59);
  a21=(a21-a59);
  a55=(a00*a55);
  a21=(a21+a55);
  a42=(a05*a42);
  a21=(a21+a42);
  if (res[0]!=0) res[0][5]=a21;
  a21=(a09*a51);
  a42=(a07*a50);
  a21=(a21+a42);
  a42=(a00*a44);
  a21=(a21+a42);
  a42=(a05*a60);
  a21=(a21+a42);
  if (res[0]!=0) res[0][6]=a21;
  a42=(a09*a12);
  a55=(a07*a13);
  a42=(a42-a55);
  a55=(a00*a17);
  a42=(a42+a55);
  a55=(a05*a43);
  a42=(a42+a55);
  if (res[0]!=0) res[0][7]=a42;
  if (res[0]!=0) res[0][8]=a52;
  if (res[0]!=0) res[0][9]=a21;
  a51=(a00*a51);
  a50=(a05*a50);
  a51=(a51-a50);
  a44=(a09*a44);
  a51=(a51-a44);
  a60=(a07*a60);
  a51=(a51+a60);
  if (res[0]!=0) res[0][10]=a51;
  a51=(a05*a13);
  a60=(a00*a12);
  a51=(a51+a60);
  a60=(a09*a17);
  a51=(a51-a60);
  a60=(a07*a43);
  a51=(a51+a60);
  if (res[0]!=0) res[0][11]=a51;
  if (res[0]!=0) res[0][12]=a46;
  if (res[0]!=0) res[0][13]=a42;
  if (res[0]!=0) res[0][14]=a51;
  a00=(a00*a13);
  a05=(a05*a12);
  a00=(a00-a05);
  a07=(a07*a17);
  a00=(a00+a07);
  a09=(a09*a43);
  a00=(a00+a09);
  if (res[0]!=0) res[0][15]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int w_totalF_nmpc_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int w_totalF_nmpc_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real w_totalF_nmpc_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* w_totalF_nmpc_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* w_totalF_nmpc_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* w_totalF_nmpc_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    case 5: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* w_totalF_nmpc_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
