/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {0, 0, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {9, 1, 1};
static const casadi_int casadi_s5[30] = 
  {10, 9, 0, 1, 2, 3, 4, 5,
  6, 10, 14, 18, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 6, 7,
  8, 9, 6, 7, 8, 9};
static const casadi_int casadi_s6[3] = {9, 0, 1};

/* w_totalF_nmpc_cost_y_e_fun_jac_ut_xt:(i0[10],i1[],i2[0],i3[],i4[4])->(o0[9],o1[10x9,18nz],o2[9x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][6] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a02=(a00*a01);
  a03=arg[0]? arg[0][7] : 0;
  a04=arg[4]? arg[4][1] : 0;
  a05=(a03*a04);
  a02=(a02+a05);
  a05=arg[0]? arg[0][8] : 0;
  a06=arg[4]? arg[4][2] : 0;
  a07=(a05*a06);
  a02=(a02+a07);
  a07=arg[0]? arg[0][9] : 0;
  a08=arg[4]? arg[4][3] : 0;
  a09=(a07*a08);
  a02=(a02+a09);
  a09=(a03*a01);
  a10=(a00*a04);
  a09=(a09-a10);
  a10=(a05*a08);
  a09=(a09-a10);
  a10=(a07*a06);
  a09=(a09+a10);
  a10=(a02*a09);
  a11=(a03*a08);
  a12=(a00*a06);
  a11=(a11-a12);
  a12=(a05*a01);
  a11=(a11+a12);
  a12=(a07*a04);
  a11=(a11-a12);
  a05=(a05*a04);
  a00=(a00*a08);
  a03=(a03*a06);
  a00=(a00+a03);
  a05=(a05-a00);
  a07=(a07*a01);
  a05=(a05+a07);
  a07=(a11*a05);
  a10=(a10-a07);
  a07=casadi_sq(a02);
  a00=casadi_sq(a05);
  a07=(a07+a00);
  a00=1.0000000000000000e-03;
  a07=(a07+a00);
  a07=sqrt(a07);
  a10=(a10/a07);
  if (res[0]!=0) res[0][6]=a10;
  a00=(a02*a11);
  a03=(a09*a05);
  a00=(a00+a03);
  a00=(a00/a07);
  if (res[0]!=0) res[0][7]=a00;
  a03=(a05/a07);
  if (res[0]!=0) res[0][8]=a03;
  a12=1.;
  if (res[1]!=0) res[1][0]=a12;
  if (res[1]!=0) res[1][1]=a12;
  if (res[1]!=0) res[1][2]=a12;
  if (res[1]!=0) res[1][3]=a12;
  if (res[1]!=0) res[1][4]=a12;
  if (res[1]!=0) res[1][5]=a12;
  a12=(a09*a01);
  a13=(a02*a04);
  a14=(a12-a13);
  a15=(a05*a06);
  a16=(a11*a08);
  a17=(a15+a16);
  a14=(a14+a17);
  a14=(a14/a07);
  a10=(a10/a07);
  a17=(a02+a02);
  a18=(a17*a01);
  a19=(a05+a05);
  a20=(a19*a08);
  a18=(a18-a20);
  a20=(a07+a07);
  a18=(a18/a20);
  a21=(a10*a18);
  a14=(a14-a21);
  if (res[1]!=0) res[1][6]=a14;
  a14=(a09*a04);
  a21=(a02*a01);
  a22=(a14+a21);
  a23=(a05*a08);
  a24=(a11*a06);
  a25=(a23-a24);
  a22=(a22-a25);
  a22=(a22/a07);
  a25=(a17*a04);
  a26=(a19*a06);
  a25=(a25-a26);
  a25=(a25/a20);
  a26=(a10*a25);
  a22=(a22-a26);
  if (res[1]!=0) res[1][7]=a22;
  a22=(a09*a06);
  a26=(a02*a08);
  a27=(a22-a26);
  a28=(a05*a01);
  a29=(a11*a04);
  a30=(a28+a29);
  a27=(a27-a30);
  a27=(a27/a07);
  a30=(a17*a06);
  a31=(a19*a04);
  a30=(a30+a31);
  a30=(a30/a20);
  a31=(a10*a30);
  a27=(a27-a31);
  if (res[1]!=0) res[1][8]=a27;
  a09=(a09*a08);
  a02=(a02*a06);
  a27=(a09+a02);
  a11=(a11*a01);
  a05=(a05*a04);
  a31=(a11-a05);
  a27=(a27-a31);
  a27=(a27/a07);
  a17=(a17*a08);
  a19=(a19*a01);
  a17=(a17+a19);
  a17=(a17/a20);
  a10=(a10*a17);
  a27=(a27-a10);
  if (res[1]!=0) res[1][9]=a27;
  a11=(a11-a02);
  a05=(a05+a09);
  a11=(a11-a05);
  a11=(a11/a07);
  a00=(a00/a07);
  a05=(a00*a18);
  a11=(a11-a05);
  if (res[1]!=0) res[1][10]=a11;
  a29=(a29+a26);
  a28=(a28-a22);
  a29=(a29+a28);
  a29=(a29/a07);
  a28=(a00*a25);
  a29=(a29-a28);
  if (res[1]!=0) res[1][11]=a29;
  a24=(a24+a21);
  a14=(a14-a23);
  a24=(a24+a14);
  a24=(a24/a07);
  a14=(a00*a30);
  a24=(a24-a14);
  if (res[1]!=0) res[1][12]=a24;
  a16=(a16-a13);
  a15=(a15+a12);
  a16=(a16+a15);
  a16=(a16/a07);
  a00=(a00*a17);
  a16=(a16-a00);
  if (res[1]!=0) res[1][13]=a16;
  a08=(a08/a07);
  a03=(a03/a07);
  a18=(a03*a18);
  a08=(a08+a18);
  a08=(-a08);
  if (res[1]!=0) res[1][14]=a08;
  a06=(a06/a07);
  a25=(a03*a25);
  a06=(a06+a25);
  a06=(-a06);
  if (res[1]!=0) res[1][15]=a06;
  a04=(a04/a07);
  a30=(a03*a30);
  a04=(a04-a30);
  if (res[1]!=0) res[1][16]=a04;
  a01=(a01/a07);
  a03=(a03*a17);
  a01=(a01-a03);
  if (res[1]!=0) res[1][17]=a01;
  return 0;
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s1;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int w_totalF_nmpc_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
