controller_choose:
  use_defalut_controller: true
  defalut_controller_type: 0           # 0: NMPC(ACADOS)  1: NMPC(IPOPT)   2: DFBC 
                                       # 3: PID           4: PX4_pose_mode

  nmpc_controller_type: 0              # 0: w_and_totalF  1: dForce
                                       # 2: Force

acados_parameters:

ipopt_parameters:
  single_predict_horizon: 0.05
  predict_steps: 20

  max_w_limit: 0.5
  max_acc_z_limit: 15.0
  max_force_limit: 10.0
  max_dforce_limit: 5.0

  min_w_limit: -0.5
  min_acc_z_limit: 0.0
  min_force_limit: -10.0
  min_dforce_limit: -5.0

  w_and_totalF_params:
    Q_pos_x: 1.0
    Q_pos_y: 1.0
    Q_pos_z: 1.0
    Q_vel_x: 0.1
    Q_vel_y: 0.1
    Q_vel_z: 0.1
    Q_quat_x: 0.01
    Q_quat_y: 0.01
    Q_quat_z: 0.01
    R_w_x: 0.1
    R_w_y: 0.1
    R_w_z: 0.1
    R_acc_z: 0.1

  force_params:
    Q_pos_x: 1.0
    Q_pos_y: 1.0
    Q_pos_z: 1.0
    Q_vel_x: 0.1
    Q_vel_y: 0.1
    Q_vel_z: 0.1
    Q_quat_x: 0.01
    Q_quat_y: 0.01
    Q_quat_z: 0.01
    Q_w_x: 0.01
    Q_w_y: 0.01
    Q_w_z: 0.01
    R_force_0: 0.1
    R_force_1: 0.1
    R_force_2: 0.1
    R_force_3: 0.1

  dforce_params:
    Q_pos_x: 1.0
    Q_pos_y: 1.0
    Q_pos_z: 1.0
    Q_vel_x: 0.1
    Q_vel_y: 0.1
    Q_vel_z: 0.1
    Q_quat_x: 0.01
    Q_quat_y: 0.01
    Q_quat_z: 0.01
    Q_w_x: 0.01
    Q_w_y: 0.01
    Q_w_z: 0.01
    Q_force_0: 0.1
    Q_force_1: 0.1
    Q_force_2: 0.1
    Q_force_3: 0.1
    R_dforce_0: 0.1
    R_dforce_1: 0.1
    R_dforce_2: 0.1
    R_dforce_3: 0.1