/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_nmpc_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[65] = {13, 13, 0, 0, 0, 0, 1, 2, 3, 10, 17, 24, 31, 37, 43, 49, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9, 11, 12, 6, 7, 8, 9, 10, 12, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s5[29] = {13, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s6[31] = {13, 4, 0, 6, 12, 18, 24, 3, 4, 5, 10, 11, 12, 3, 4, 5, 10, 11, 12, 3, 4, 5, 10, 11, 12, 3, 4, 5, 10, 11, 12};
static const casadi_int casadi_s7[3] = {13, 0, 0};

/* f_nmpc_impl_dae_jac_x_xdot_u_z:(i0[13],i1[13],i2[4],i3[0],i4[],i5[4])->(o0[13x13,49nz],o1[13x13,13nz],o2[13x4,24nz],o3[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a3, a4, a5, a6, a7, a8, a9;
  a0=-1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][8] : 0;
  a1=arg[0]? arg[0][6] : 0;
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][7] : 0;
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a4=casadi_sq(a0);
  a2=(a2+a4);
  a4=arg[0]? arg[0][9] : 0;
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a2=sqrt(a2);
  a0=(a0/a2);
  a5=arg[2]? arg[2][0] : 0;
  a6=arg[2]? arg[2][1] : 0;
  a5=(a5+a6);
  a6=arg[2]? arg[2][2] : 0;
  a5=(a5+a6);
  a6=arg[2]? arg[2][3] : 0;
  a5=(a5+a6);
  a6=(a0*a5);
  a7=(1./a2);
  a1=(a1/a2);
  a8=(a1/a2);
  a9=(a8*a1);
  a9=(a7-a9);
  a10=(a6*a9);
  a11=(a0/a2);
  a12=(a11*a1);
  a13=(a5*a12);
  a14=(a1*a13);
  a10=(a10-a14);
  a3=(a3/a2);
  a4=(a4/a2);
  a14=(a4/a2);
  a15=(a14*a1);
  a16=(a5*a15);
  a17=(a3*a16);
  a18=(a4*a5);
  a2=(a3/a2);
  a19=(a2*a1);
  a20=(a18*a19);
  a17=(a17+a20);
  a10=(a10-a17);
  a17=(a5*a19);
  a20=(a4*a17);
  a21=(a3*a5);
  a22=(a21*a15);
  a20=(a20+a22);
  a10=(a10-a20);
  a20=(a5*a9);
  a22=(a0*a20);
  a23=(a1*a5);
  a24=(a23*a12);
  a22=(a22-a24);
  a10=(a10+a22);
  a10=(-a10);
  if (res[0]!=0) res[0][3]=a10;
  a10=(a0*a16);
  a22=(a18*a12);
  a10=(a10+a22);
  a22=(a4*a13);
  a24=(a6*a15);
  a22=(a22+a24);
  a10=(a10+a22);
  a22=(a21*a9);
  a24=(a1*a17);
  a22=(a22-a24);
  a10=(a10+a22);
  a22=(a3*a20);
  a24=(a23*a19);
  a22=(a22-a24);
  a10=(a10+a22);
  if (res[0]!=0) res[0][4]=a10;
  a13=(a0*a13);
  a10=(a6*a12);
  a13=(a13+a10);
  a16=(a4*a16);
  a10=(a18*a15);
  a16=(a16+a10);
  a13=(a13-a16);
  a17=(a3*a17);
  a16=(a21*a19);
  a17=(a17+a16);
  a13=(a13+a17);
  a20=(a1*a20);
  a17=(a23*a9);
  a20=(a20+a17);
  a13=(a13+a20);
  a13=(-a13);
  if (res[0]!=0) res[0][5]=a13;
  a13=5.0000000000000000e-01;
  a20=arg[0]? arg[0][10] : 0;
  a17=(a20*a19);
  a16=arg[0]? arg[0][11] : 0;
  a10=(a16*a12);
  a17=(a17+a10);
  a10=arg[0]? arg[0][12] : 0;
  a22=(a10*a15);
  a17=(a17+a22);
  a17=(a13*a17);
  a17=(-a17);
  if (res[0]!=0) res[0][6]=a17;
  a17=(a20*a9);
  a22=(a10*a12);
  a17=(a17-a22);
  a22=(a16*a15);
  a17=(a17+a22);
  a17=(a13*a17);
  a17=(-a17);
  if (res[0]!=0) res[0][7]=a17;
  a17=(a16*a9);
  a22=(a10*a19);
  a17=(a17+a22);
  a15=(a20*a15);
  a17=(a17-a15);
  a17=(a13*a17);
  a17=(-a17);
  if (res[0]!=0) res[0][8]=a17;
  a9=(a10*a9);
  a19=(a16*a19);
  a9=(a9-a19);
  a12=(a20*a12);
  a9=(a9+a12);
  a9=(a13*a9);
  a9=(-a9);
  if (res[0]!=0) res[0][9]=a9;
  a9=(a2*a3);
  a9=(a7-a9);
  a12=(a18*a9);
  a19=(a14*a3);
  a17=(a5*a19);
  a15=(a3*a17);
  a12=(a12-a15);
  a15=(a11*a3);
  a22=(a5*a15);
  a24=(a1*a22);
  a25=(a8*a3);
  a26=(a6*a25);
  a24=(a24+a26);
  a12=(a12-a24);
  a24=(a5*a9);
  a26=(a4*a24);
  a27=(a21*a19);
  a26=(a26-a27);
  a12=(a12+a26);
  a26=(a5*a25);
  a27=(a0*a26);
  a28=(a23*a15);
  a27=(a27+a28);
  a12=(a12-a27);
  a12=(-a12);
  if (res[0]!=0) res[0][10]=a12;
  a12=(a0*a17);
  a27=(a18*a15);
  a12=(a12+a27);
  a27=(a4*a22);
  a28=(a6*a19);
  a27=(a27+a28);
  a12=(a12+a27);
  a27=(a1*a24);
  a28=(a21*a25);
  a27=(a27-a28);
  a12=(a12+a27);
  a27=(a23*a9);
  a28=(a3*a26);
  a27=(a27-a28);
  a12=(a12+a27);
  if (res[0]!=0) res[0][11]=a12;
  a22=(a0*a22);
  a12=(a6*a15);
  a22=(a22+a12);
  a17=(a4*a17);
  a12=(a18*a19);
  a17=(a17+a12);
  a22=(a22-a17);
  a24=(a3*a24);
  a17=(a21*a9);
  a24=(a24+a17);
  a22=(a22-a24);
  a26=(a1*a26);
  a24=(a23*a25);
  a26=(a26+a24);
  a22=(a22-a26);
  a22=(-a22);
  if (res[0]!=0) res[0][12]=a22;
  a22=(a20*a9);
  a26=(a16*a15);
  a22=(a22-a26);
  a26=(a10*a19);
  a22=(a22-a26);
  a22=(a13*a22);
  if (res[0]!=0) res[0][13]=a22;
  a22=(a16*a19);
  a26=(a20*a25);
  a24=(a10*a15);
  a26=(a26+a24);
  a22=(a22-a26);
  a22=(a13*a22);
  a22=(-a22);
  if (res[0]!=0) res[0][14]=a22;
  a22=(a16*a25);
  a26=(a10*a9);
  a22=(a22+a26);
  a19=(a20*a19);
  a22=(a22+a19);
  a22=(a13*a22);
  if (res[0]!=0) res[0][15]=a22;
  a9=(a16*a9);
  a25=(a10*a25);
  a9=(a9-a25);
  a15=(a20*a15);
  a9=(a9+a15);
  a9=(a13*a9);
  a9=(-a9);
  if (res[0]!=0) res[0][16]=a9;
  a9=(a11*a0);
  a9=(a7-a9);
  a15=(a5*a9);
  a25=(a1*a15);
  a22=(a8*a0);
  a19=(a6*a22);
  a25=(a25-a19);
  a19=(a14*a0);
  a26=(a5*a19);
  a24=(a3*a26);
  a17=(a2*a0);
  a12=(a18*a17);
  a24=(a24+a12);
  a25=(a25-a24);
  a24=(a5*a17);
  a12=(a4*a24);
  a27=(a21*a19);
  a12=(a12+a27);
  a25=(a25-a12);
  a12=(a23*a9);
  a27=(a5*a22);
  a28=(a0*a27);
  a12=(a12-a28);
  a25=(a25+a12);
  a25=(-a25);
  if (res[0]!=0) res[0][17]=a25;
  a25=(a18*a9);
  a12=(a0*a26);
  a25=(a25-a12);
  a12=(a4*a15);
  a28=(a6*a19);
  a12=(a12-a28);
  a25=(a25+a12);
  a12=(a1*a24);
  a28=(a21*a22);
  a12=(a12+a28);
  a25=(a25+a12);
  a12=(a3*a27);
  a28=(a23*a17);
  a12=(a12+a28);
  a25=(a25+a12);
  a25=(-a25);
  if (res[0]!=0) res[0][18]=a25;
  a24=(a3*a24);
  a25=(a21*a17);
  a24=(a24+a25);
  a26=(a4*a26);
  a25=(a18*a19);
  a26=(a26+a25);
  a15=(a0*a15);
  a25=(a6*a9);
  a15=(a15+a25);
  a26=(a26+a15);
  a24=(a24-a26);
  a27=(a1*a27);
  a26=(a23*a22);
  a27=(a27+a26);
  a24=(a24-a27);
  a24=(-a24);
  if (res[0]!=0) res[0][19]=a24;
  a24=(a16*a9);
  a27=(a20*a17);
  a24=(a24-a27);
  a27=(a10*a19);
  a24=(a24-a27);
  a24=(a13*a24);
  if (res[0]!=0) res[0][20]=a24;
  a24=(a10*a9);
  a27=(a20*a22);
  a24=(a24-a27);
  a27=(a16*a19);
  a24=(a24+a27);
  a24=(a13*a24);
  a24=(-a24);
  if (res[0]!=0) res[0][21]=a24;
  a24=(a10*a17);
  a27=(a16*a22);
  a24=(a24-a27);
  a19=(a20*a19);
  a24=(a24-a19);
  a24=(a13*a24);
  a24=(-a24);
  if (res[0]!=0) res[0][22]=a24;
  a22=(a10*a22);
  a17=(a16*a17);
  a22=(a22+a17);
  a9=(a20*a9);
  a22=(a22+a9);
  a22=(a13*a22);
  if (res[0]!=0) res[0][23]=a22;
  a14=(a14*a4);
  a7=(a7-a14);
  a14=(a5*a7);
  a22=(a3*a14);
  a2=(a2*a4);
  a9=(a18*a2);
  a22=(a22-a9);
  a11=(a11*a4);
  a9=(a5*a11);
  a17=(a1*a9);
  a8=(a8*a4);
  a24=(a6*a8);
  a17=(a17+a24);
  a22=(a22-a17);
  a17=(a21*a7);
  a24=(a5*a2);
  a19=(a4*a24);
  a17=(a17-a19);
  a22=(a22+a17);
  a5=(a5*a8);
  a17=(a0*a5);
  a19=(a23*a11);
  a17=(a17+a19);
  a22=(a22-a17);
  a22=(-a22);
  if (res[0]!=0) res[0][24]=a22;
  a22=(a0*a14);
  a17=(a18*a11);
  a22=(a22-a17);
  a17=(a6*a7);
  a19=(a4*a9);
  a17=(a17-a19);
  a22=(a22+a17);
  a17=(a1*a24);
  a19=(a21*a8);
  a17=(a17+a19);
  a22=(a22+a17);
  a17=(a3*a5);
  a19=(a23*a2);
  a17=(a17+a19);
  a22=(a22+a17);
  a22=(-a22);
  if (res[0]!=0) res[0][25]=a22;
  a14=(a4*a14);
  a18=(a18*a7);
  a14=(a14+a18);
  a9=(a0*a9);
  a6=(a6*a11);
  a9=(a9+a6);
  a14=(a14+a9);
  a24=(a3*a24);
  a21=(a21*a2);
  a24=(a24+a21);
  a14=(a14+a24);
  a5=(a1*a5);
  a23=(a23*a8);
  a5=(a5+a23);
  a14=(a14-a5);
  a14=(-a14);
  if (res[0]!=0) res[0][26]=a14;
  a14=(a10*a7);
  a5=(a20*a2);
  a23=(a16*a11);
  a5=(a5+a23);
  a14=(a14-a5);
  a14=(a13*a14);
  if (res[0]!=0) res[0][27]=a14;
  a14=(a20*a8);
  a5=(a10*a11);
  a14=(a14+a5);
  a5=(a16*a7);
  a14=(a14+a5);
  a14=(a13*a14);
  if (res[0]!=0) res[0][28]=a14;
  a14=(a10*a2);
  a5=(a16*a8);
  a14=(a14-a5);
  a7=(a20*a7);
  a14=(a14+a7);
  a14=(a13*a14);
  a14=(-a14);
  if (res[0]!=0) res[0][29]=a14;
  a11=(a20*a11);
  a8=(a10*a8);
  a2=(a16*a2);
  a8=(a8+a2);
  a11=(a11-a8);
  a11=(a13*a11);
  a11=(-a11);
  if (res[0]!=0) res[0][30]=a11;
  a11=(a13*a3);
  if (res[0]!=0) res[0][31]=a11;
  a8=(a13*a1);
  a8=(-a8);
  if (res[0]!=0) res[0][32]=a8;
  a2=(a13*a4);
  a14=(-a2);
  if (res[0]!=0) res[0][33]=a14;
  a13=(a13*a0);
  if (res[0]!=0) res[0][34]=a13;
  a14=3.2018645935611460e+02;
  a7=3.2812086419999999e-03;
  a5=(a7*a10);
  a23=6.8493920203700001e-03;
  a24=(a23*a10);
  a5=(a5-a24);
  a5=(a14*a5);
  if (res[0]!=0) res[0][35]=a5;
  a5=1.4599835971222166e+02;
  a21=3.1231801682400002e-03;
  a9=(a21*a16);
  a6=(a7*a16);
  a6=(a9-a6);
  a6=(a5*a6);
  if (res[0]!=0) res[0][36]=a6;
  if (res[0]!=0) res[0][37]=a13;
  if (res[0]!=0) res[0][38]=a2;
  if (res[0]!=0) res[0][39]=a8;
  a6=(-a11);
  if (res[0]!=0) res[0][40]=a6;
  a6=3.0476574613386015e+02;
  a10=(a21*a10);
  a24=(a24-a10);
  a24=(a6*a24);
  if (res[0]!=0) res[0][41]=a24;
  a21=(a21*a20);
  a7=(a7*a20);
  a21=(a21-a7);
  a5=(a5*a21);
  if (res[0]!=0) res[0][42]=a5;
  if (res[0]!=0) res[0][43]=a2;
  a13=(-a13);
  if (res[0]!=0) res[0][44]=a13;
  if (res[0]!=0) res[0][45]=a11;
  if (res[0]!=0) res[0][46]=a8;
  a16=(a23*a16);
  a16=(a16-a9);
  a6=(a6*a16);
  if (res[0]!=0) res[0][47]=a6;
  a23=(a23*a20);
  a7=(a7-a23);
  a14=(a14*a7);
  if (res[0]!=0) res[0][48]=a14;
  a14=1.;
  if (res[1]!=0) res[1][0]=a14;
  if (res[1]!=0) res[1][1]=a14;
  if (res[1]!=0) res[1][2]=a14;
  if (res[1]!=0) res[1][3]=a14;
  if (res[1]!=0) res[1][4]=a14;
  if (res[1]!=0) res[1][5]=a14;
  if (res[1]!=0) res[1][6]=a14;
  if (res[1]!=0) res[1][7]=a14;
  if (res[1]!=0) res[1][8]=a14;
  if (res[1]!=0) res[1][9]=a14;
  if (res[1]!=0) res[1][10]=a14;
  if (res[1]!=0) res[1][11]=a14;
  if (res[1]!=0) res[1][12]=a14;
  a14=(a3*a4);
  a7=(a1*a0);
  a14=(a14+a7);
  a7=(a4*a3);
  a14=(a14+a7);
  a7=(a0*a1);
  a14=(a14+a7);
  a14=(-a14);
  if (res[2]!=0) res[2][0]=a14;
  a7=(a0*a4);
  a23=(a4*a0);
  a7=(a7+a23);
  a23=(a1*a3);
  a7=(a7-a23);
  a23=(a3*a1);
  a7=(a7-a23);
  a7=(-a7);
  if (res[2]!=0) res[2][1]=a7;
  a4=casadi_sq(a4);
  a0=casadi_sq(a0);
  a4=(a4-a0);
  a3=casadi_sq(a3);
  a4=(a4-a3);
  a1=casadi_sq(a1);
  a4=(a4+a1);
  a4=(-a4);
  if (res[2]!=0) res[2][2]=a4;
  a1=2.6937740720578795e+01;
  if (res[2]!=0) res[2][3]=a1;
  a3=-2.8300752081852441e+01;
  if (res[2]!=0) res[2][4]=a3;
  a0=-5.6536404814960717e+00;
  if (res[2]!=0) res[2][5]=a0;
  if (res[2]!=0) res[2][6]=a14;
  if (res[2]!=0) res[2][7]=a7;
  if (res[2]!=0) res[2][8]=a4;
  a23=-2.6937740720578795e+01;
  if (res[2]!=0) res[2][9]=a23;
  a20=2.8300752081852441e+01;
  if (res[2]!=0) res[2][10]=a20;
  if (res[2]!=0) res[2][11]=a0;
  if (res[2]!=0) res[2][12]=a14;
  if (res[2]!=0) res[2][13]=a7;
  if (res[2]!=0) res[2][14]=a4;
  if (res[2]!=0) res[2][15]=a23;
  if (res[2]!=0) res[2][16]=a3;
  a3=5.6536404814960717e+00;
  if (res[2]!=0) res[2][17]=a3;
  if (res[2]!=0) res[2][18]=a14;
  if (res[2]!=0) res[2][19]=a7;
  if (res[2]!=0) res[2][20]=a4;
  if (res[2]!=0) res[2][21]=a1;
  if (res[2]!=0) res[2][22]=a20;
  if (res[2]!=0) res[2][23]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_nmpc_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_nmpc_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_nmpc_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_nmpc_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_nmpc_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int f_nmpc_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real f_nmpc_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_nmpc_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_nmpc_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_nmpc_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_nmpc_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
