/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_nmpc_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};

/* f_nmpc_impl_dae_fun:(i0[13],i1[13],i2[4],i3[0],i4[],i5[4])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][3] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a1=arg[0]? arg[0][4] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a1=arg[0]? arg[0][5] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a1=arg[0]? arg[0][9] : 0;
  a2=arg[0]? arg[0][6] : 0;
  a3=casadi_sq(a2);
  a4=arg[0]? arg[0][7] : 0;
  a5=casadi_sq(a4);
  a3=(a3+a5);
  a5=arg[0]? arg[0][8] : 0;
  a6=casadi_sq(a5);
  a3=(a3+a6);
  a6=casadi_sq(a1);
  a3=(a3+a6);
  a3=sqrt(a3);
  a1=(a1/a3);
  a6=arg[2]? arg[2][0] : 0;
  a7=arg[2]? arg[2][1] : 0;
  a8=(a6+a7);
  a9=arg[2]? arg[2][2] : 0;
  a10=(a8+a9);
  a11=arg[2]? arg[2][3] : 0;
  a10=(a10+a11);
  a12=(a1*a10);
  a4=(a4/a3);
  a13=(a12*a4);
  a5=(a5/a3);
  a14=(a5*a10);
  a2=(a2/a3);
  a3=(a14*a2);
  a13=(a13+a3);
  a3=(a4*a10);
  a15=(a3*a1);
  a13=(a13+a15);
  a10=(a2*a10);
  a15=(a10*a5);
  a13=(a13+a15);
  a0=(a0-a13);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a13=(a12*a5);
  a15=(a14*a1);
  a13=(a13+a15);
  a15=(a3*a2);
  a13=(a13-a15);
  a15=(a10*a4);
  a13=(a13-a15);
  a0=(a0-a13);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a12=(a12*a1);
  a14=(a14*a5);
  a12=(a12-a14);
  a3=(a3*a4);
  a12=(a12-a3);
  a10=(a10*a2);
  a12=(a12+a10);
  a10=9.8015000000000008e+00;
  a12=(a12-a10);
  a0=(a0-a12);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][6] : 0;
  a12=5.0000000000000000e-01;
  a10=arg[0]? arg[0][10] : 0;
  a3=(a4*a10);
  a14=arg[0]? arg[0][11] : 0;
  a13=(a5*a14);
  a3=(a3+a13);
  a13=arg[0]? arg[0][12] : 0;
  a15=(a1*a13);
  a3=(a3+a15);
  a3=(a12*a3);
  a0=(a0+a3);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][7] : 0;
  a3=(a2*a10);
  a15=(a5*a13);
  a3=(a3+a15);
  a15=(a1*a14);
  a3=(a3-a15);
  a3=(a12*a3);
  a0=(a0-a3);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1]? arg[1][8] : 0;
  a3=(a2*a14);
  a15=(a4*a13);
  a3=(a3-a15);
  a1=(a1*a10);
  a3=(a3+a1);
  a3=(a12*a3);
  a0=(a0-a3);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][9] : 0;
  a2=(a2*a13);
  a4=(a4*a14);
  a2=(a2+a4);
  a5=(a5*a10);
  a2=(a2-a5);
  a12=(a12*a2);
  a0=(a0-a12);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][10] : 0;
  a12=3.0476574613386015e+02;
  a2=1.2500000000000000e-01;
  a5=-7.0710678118654757e-01;
  a4=(a5*a6);
  a3=7.0710678118654757e-01;
  a1=(a3*a7);
  a4=(a4+a1);
  a1=(a3*a9);
  a4=(a4+a1);
  a15=(a5*a11);
  a4=(a4+a15);
  a4=(a2*a4);
  a16=6.8493920203700001e-03;
  a16=(a16*a13);
  a17=(a14*a16);
  a18=3.1231801682400002e-03;
  a18=(a18*a14);
  a19=(a13*a18);
  a17=(a17-a19);
  a4=(a4-a17);
  a12=(a12*a4);
  a0=(a0-a12);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a12=3.2018645935611460e+02;
  a3=(a3*a6);
  a5=(a5*a7);
  a3=(a3+a5);
  a3=(a3+a1);
  a3=(a3+a15);
  a2=(a2*a3);
  a3=3.2812086419999999e-03;
  a3=(a3*a10);
  a13=(a13*a3);
  a16=(a10*a16);
  a13=(a13-a16);
  a2=(a2-a13);
  a12=(a12*a2);
  a0=(a0-a12);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[1]? arg[1][12] : 0;
  a12=1.4599835971222166e+02;
  a2=3.8724000000000001e-02;
  a8=(a8-a9);
  a8=(a8-a11);
  a2=(a2*a8);
  a10=(a10*a18);
  a14=(a14*a3);
  a10=(a10-a14);
  a2=(a2-a10);
  a12=(a12*a2);
  a0=(a0-a12);
  if (res[0]!=0) res[0][12]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_nmpc_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_nmpc_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_nmpc_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_nmpc_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_nmpc_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int f_nmpc_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_nmpc_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_nmpc_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_nmpc_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_nmpc_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_nmpc_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_nmpc_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
